# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marvglo', '0002_employee_admin_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='marvglo.Team'),
        ),
    ]
