# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvglo', '0003_auto_20170124_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
