# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvglo', '0004_auto_20170124_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.IntegerField(default=3),
        ),
    ]
