# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvglo', '0005_auto_20170130_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sold_at_price',
            field=models.FloatField(default=0),
        ),
    ]
