# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvglo', '0006_transaction_sold_at_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[(b'Director', b'Director'), (b'Assistant Director', b'Assistant Director'), (b'Assistant Supervisor', b'Assistant Supervisor'), (b'Supervisor', b'Supervisor')], default='Supervisor', max_length=50),
        ),
    ]
