# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marvglo', '0008_auto_20170308_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
