# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-23 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvglo', '0009_transaction_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
