# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marvglo', '0011_auto_20170323_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='discounted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(choices=[(b'Director', b'Director'), (b'Assistant Director', b'Assistant Director'), (b'Supervisor', b'Supervisor'), (b'Assistant Supervisor', b'Assistant Supervisor')], default='Supervisor', max_length=50),
        ),
    ]
